### ISSUE TITLE
Mod encountered an error during event phase

### ISSUE THREAD

**Issue by GitUser14975** [NeRdTheNed/More-bows#13] opened 2023-06-29 13:09 UTC
Hi, I got an error saying that more bows enountered an error during event setup phase(?) or something like that

https://gist.github.com/TenKotowsky/eb55763fc3561c89dba37ca444f23c7a

**Comment by NeRdTheNed** [comment] 2023-06-30 05:47
Found the cause of the bug: ItemProperties.register needs to be handled in a thread safe way on Forge. Working on a fix.

**Comment by NeRdTheNed** [comment] 2023-06-30 06:22
@TenKotowsky Does this snapshot build fix the issue? https://github.com/NeRdTheNed/More-bows/suites/13970833813/artifacts/778952066

**Comment by NeRdTheNed** [comment] 2023-07-01 14:29
Likely fixed in v1.0.12.

**Closed as completed by NeRdTheNed** 2023-07-01 14:29 UTC
Labels: bug, 1.16.x.forge, 1.17.x.forge, 1.18.x.forge, 1.19.2.forge, 1.19.3.forge, 1.19.x.forge, 1.20.x.forge, forge
